<?php if ($block->getCollection()) : ?>
    <div class="vs7_promowidget-container">
    <?php if ($block->getCollection()->getSize() > 0) : ?>
        <?php foreach ($block->getCollection() as $banner): ?>
            <div class="vs7_promowidget-banner">
                <a href="<?php echo $banner->getUrlKey(); ?>">
                    <img src="<?php echo $banner->getImage(); ?>" alt="<?php echo $banner->getName(); ?>" title="<?php echo $banner->getName(); ?>"/>
                </a>
            </div>
        <?php endforeach; ?>
    <?php endif;?>
    </div>
<?php endif;?>
